#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCity.GoodsManager
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SMDB")]
	public partial class PagedDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertSCarInfo(SCarInfo instance);
    partial void UpdateSCarInfo(SCarInfo instance);
    partial void DeleteSCarInfo(SCarInfo instance);
    partial void InsertSCar(SCar instance);
    partial void UpdateSCar(SCar instance);
    partial void DeleteSCar(SCar instance);
    partial void InsertGoods(Goods instance);
    partial void UpdateGoods(Goods instance);
    partial void DeleteGoods(Goods instance);
    partial void InsertGoodEvaluate(GoodEvaluate instance);
    partial void UpdateGoodEvaluate(GoodEvaluate instance);
    partial void DeleteGoodEvaluate(GoodEvaluate instance);
    partial void InsertUsers(Users instance);
    partial void UpdateUsers(Users instance);
    partial void DeleteUsers(Users instance);
    #endregion
		
		public PagedDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SMDB"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PagedDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PagedDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PagedDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PagedDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SCarInfo> SCarInfo
		{
			get
			{
				return this.GetTable<SCarInfo>();
			}
		}
		
		public System.Data.Linq.Table<SCar> SCar
		{
			get
			{
				return this.GetTable<SCar>();
			}
		}
		
		public System.Data.Linq.Table<Goods> Goods
		{
			get
			{
				return this.GetTable<Goods>();
			}
		}
		
		public System.Data.Linq.Table<GoodEvaluate> GoodEvaluate
		{
			get
			{
				return this.GetTable<GoodEvaluate>();
			}
		}
		
		public System.Data.Linq.Table<Users> Users
		{
			get
			{
				return this.GetTable<Users>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SCarInfo")]
	public partial class SCarInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sciID;
		
		private int _scID;
		
		private int _gdID;
		
		private int _scNum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsciIDChanging(int value);
    partial void OnsciIDChanged();
    partial void OnscIDChanging(int value);
    partial void OnscIDChanged();
    partial void OngdIDChanging(int value);
    partial void OngdIDChanged();
    partial void OnscNumChanging(int value);
    partial void OnscNumChanged();
    #endregion
		
		public SCarInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sciID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sciID
		{
			get
			{
				return this._sciID;
			}
			set
			{
				if ((this._sciID != value))
				{
					this.OnsciIDChanging(value);
					this.SendPropertyChanging();
					this._sciID = value;
					this.SendPropertyChanged("sciID");
					this.OnsciIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scID", DbType="Int NOT NULL")]
		public int scID
		{
			get
			{
				return this._scID;
			}
			set
			{
				if ((this._scID != value))
				{
					this.OnscIDChanging(value);
					this.SendPropertyChanging();
					this._scID = value;
					this.SendPropertyChanged("scID");
					this.OnscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdID", DbType="Int NOT NULL")]
		public int gdID
		{
			get
			{
				return this._gdID;
			}
			set
			{
				if ((this._gdID != value))
				{
					this.OngdIDChanging(value);
					this.SendPropertyChanging();
					this._gdID = value;
					this.SendPropertyChanged("gdID");
					this.OngdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scNum", DbType="Int NOT NULL")]
		public int scNum
		{
			get
			{
				return this._scNum;
			}
			set
			{
				if ((this._scNum != value))
				{
					this.OnscNumChanging(value);
					this.SendPropertyChanging();
					this._scNum = value;
					this.SendPropertyChanged("scNum");
					this.OnscNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SCar")]
	public partial class SCar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _scID;
		
		private int _uID;
		
		private System.DateTime _scAddTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnscIDChanging(int value);
    partial void OnscIDChanged();
    partial void OnuIDChanging(int value);
    partial void OnuIDChanged();
    partial void OnscAddTimeChanging(System.DateTime value);
    partial void OnscAddTimeChanged();
    #endregion
		
		public SCar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int scID
		{
			get
			{
				return this._scID;
			}
			set
			{
				if ((this._scID != value))
				{
					this.OnscIDChanging(value);
					this.SendPropertyChanging();
					this._scID = value;
					this.SendPropertyChanged("scID");
					this.OnscIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uID", DbType="Int NOT NULL")]
		public int uID
		{
			get
			{
				return this._uID;
			}
			set
			{
				if ((this._uID != value))
				{
					this.OnuIDChanging(value);
					this.SendPropertyChanging();
					this._uID = value;
					this.SendPropertyChanged("uID");
					this.OnuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scAddTime", DbType="DateTime NOT NULL")]
		public System.DateTime scAddTime
		{
			get
			{
				return this._scAddTime;
			}
			set
			{
				if ((this._scAddTime != value))
				{
					this.OnscAddTimeChanging(value);
					this.SendPropertyChanging();
					this._scAddTime = value;
					this.SendPropertyChanged("scAddTime");
					this.OnscAddTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Goods")]
	public partial class Goods : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gdID;
		
		private int _tID;
		
		private string _gdCode;
		
		private string _gdName;
		
		private System.Nullable<double> _gdPrice;
		
		private System.Nullable<int> _gdQuantity;
		
		private System.Nullable<int> _gdSaleQty;
		
		private double _gdFeight;
		
		private string _gdCity;
		
		private string _gdImage;
		
		private string _gdInfo;
		
		private System.Nullable<System.DateTime> _gdAddTime;
		
		private System.Nullable<int> _gdEvNum;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngdIDChanging(int value);
    partial void OngdIDChanged();
    partial void OntIDChanging(int value);
    partial void OntIDChanged();
    partial void OngdCodeChanging(string value);
    partial void OngdCodeChanged();
    partial void OngdNameChanging(string value);
    partial void OngdNameChanged();
    partial void OngdPriceChanging(System.Nullable<double> value);
    partial void OngdPriceChanged();
    partial void OngdQuantityChanging(System.Nullable<int> value);
    partial void OngdQuantityChanged();
    partial void OngdSaleQtyChanging(System.Nullable<int> value);
    partial void OngdSaleQtyChanged();
    partial void OngdFeightChanging(double value);
    partial void OngdFeightChanged();
    partial void OngdCityChanging(string value);
    partial void OngdCityChanged();
    partial void OngdImageChanging(string value);
    partial void OngdImageChanged();
    partial void OngdInfoChanging(string value);
    partial void OngdInfoChanged();
    partial void OngdAddTimeChanging(System.Nullable<System.DateTime> value);
    partial void OngdAddTimeChanged();
    partial void OngdEvNumChanging(System.Nullable<int> value);
    partial void OngdEvNumChanged();
    #endregion
		
		public Goods()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gdID
		{
			get
			{
				return this._gdID;
			}
			set
			{
				if ((this._gdID != value))
				{
					this.OngdIDChanging(value);
					this.SendPropertyChanging();
					this._gdID = value;
					this.SendPropertyChanged("gdID");
					this.OngdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tID", DbType="Int NOT NULL")]
		public int tID
		{
			get
			{
				return this._tID;
			}
			set
			{
				if ((this._tID != value))
				{
					this.OntIDChanging(value);
					this.SendPropertyChanging();
					this._tID = value;
					this.SendPropertyChanged("tID");
					this.OntIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdCode", DbType="VarChar(50)")]
		public string gdCode
		{
			get
			{
				return this._gdCode;
			}
			set
			{
				if ((this._gdCode != value))
				{
					this.OngdCodeChanging(value);
					this.SendPropertyChanging();
					this._gdCode = value;
					this.SendPropertyChanged("gdCode");
					this.OngdCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string gdName
		{
			get
			{
				return this._gdName;
			}
			set
			{
				if ((this._gdName != value))
				{
					this.OngdNameChanging(value);
					this.SendPropertyChanging();
					this._gdName = value;
					this.SendPropertyChanged("gdName");
					this.OngdNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdPrice", DbType="Float")]
		public System.Nullable<double> gdPrice
		{
			get
			{
				return this._gdPrice;
			}
			set
			{
				if ((this._gdPrice != value))
				{
					this.OngdPriceChanging(value);
					this.SendPropertyChanging();
					this._gdPrice = value;
					this.SendPropertyChanged("gdPrice");
					this.OngdPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdQuantity", DbType="Int")]
		public System.Nullable<int> gdQuantity
		{
			get
			{
				return this._gdQuantity;
			}
			set
			{
				if ((this._gdQuantity != value))
				{
					this.OngdQuantityChanging(value);
					this.SendPropertyChanging();
					this._gdQuantity = value;
					this.SendPropertyChanged("gdQuantity");
					this.OngdQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdSaleQty", DbType="Int")]
		public System.Nullable<int> gdSaleQty
		{
			get
			{
				return this._gdSaleQty;
			}
			set
			{
				if ((this._gdSaleQty != value))
				{
					this.OngdSaleQtyChanging(value);
					this.SendPropertyChanging();
					this._gdSaleQty = value;
					this.SendPropertyChanged("gdSaleQty");
					this.OngdSaleQtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdFeight", DbType="Float NOT NULL")]
		public double gdFeight
		{
			get
			{
				return this._gdFeight;
			}
			set
			{
				if ((this._gdFeight != value))
				{
					this.OngdFeightChanging(value);
					this.SendPropertyChanging();
					this._gdFeight = value;
					this.SendPropertyChanged("gdFeight");
					this.OngdFeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdCity", DbType="VarChar(50)")]
		public string gdCity
		{
			get
			{
				return this._gdCity;
			}
			set
			{
				if ((this._gdCity != value))
				{
					this.OngdCityChanging(value);
					this.SendPropertyChanging();
					this._gdCity = value;
					this.SendPropertyChanged("gdCity");
					this.OngdCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdImage", DbType="VarChar(100)")]
		public string gdImage
		{
			get
			{
				return this._gdImage;
			}
			set
			{
				if ((this._gdImage != value))
				{
					this.OngdImageChanging(value);
					this.SendPropertyChanging();
					this._gdImage = value;
					this.SendPropertyChanged("gdImage");
					this.OngdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdInfo", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string gdInfo
		{
			get
			{
				return this._gdInfo;
			}
			set
			{
				if ((this._gdInfo != value))
				{
					this.OngdInfoChanging(value);
					this.SendPropertyChanging();
					this._gdInfo = value;
					this.SendPropertyChanged("gdInfo");
					this.OngdInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdAddTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> gdAddTime
		{
			get
			{
				return this._gdAddTime;
			}
			set
			{
				if ((this._gdAddTime != value))
				{
					this.OngdAddTimeChanging(value);
					this.SendPropertyChanging();
					this._gdAddTime = value;
					this.SendPropertyChanged("gdAddTime");
					this.OngdAddTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdEvNum", DbType="Int")]
		public System.Nullable<int> gdEvNum
		{
			get
			{
				return this._gdEvNum;
			}
			set
			{
				if ((this._gdEvNum != value))
				{
					this.OngdEvNumChanging(value);
					this.SendPropertyChanging();
					this._gdEvNum = value;
					this.SendPropertyChanged("gdEvNum");
					this.OngdEvNumChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GoodEvaluate")]
	public partial class GoodEvaluate : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _geID;
		
		private int _uID;
		
		private int _gdID;
		
		private string _geContent;
		
		private System.DateTime _geAddTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngeIDChanging(int value);
    partial void OngeIDChanged();
    partial void OnuIDChanging(int value);
    partial void OnuIDChanged();
    partial void OngdIDChanging(int value);
    partial void OngdIDChanged();
    partial void OngeContentChanging(string value);
    partial void OngeContentChanged();
    partial void OngeAddTimeChanging(System.DateTime value);
    partial void OngeAddTimeChanged();
    #endregion
		
		public GoodEvaluate()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int geID
		{
			get
			{
				return this._geID;
			}
			set
			{
				if ((this._geID != value))
				{
					this.OngeIDChanging(value);
					this.SendPropertyChanging();
					this._geID = value;
					this.SendPropertyChanged("geID");
					this.OngeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uID", DbType="Int NOT NULL")]
		public int uID
		{
			get
			{
				return this._uID;
			}
			set
			{
				if ((this._uID != value))
				{
					this.OnuIDChanging(value);
					this.SendPropertyChanging();
					this._uID = value;
					this.SendPropertyChanged("uID");
					this.OnuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gdID", DbType="Int NOT NULL")]
		public int gdID
		{
			get
			{
				return this._gdID;
			}
			set
			{
				if ((this._gdID != value))
				{
					this.OngdIDChanging(value);
					this.SendPropertyChanging();
					this._gdID = value;
					this.SendPropertyChanged("gdID");
					this.OngdIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geContent", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string geContent
		{
			get
			{
				return this._geContent;
			}
			set
			{
				if ((this._geContent != value))
				{
					this.OngeContentChanging(value);
					this.SendPropertyChanging();
					this._geContent = value;
					this.SendPropertyChanged("geContent");
					this.OngeContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_geAddTime", DbType="DateTime NOT NULL")]
		public System.DateTime geAddTime
		{
			get
			{
				return this._geAddTime;
			}
			set
			{
				if ((this._geAddTime != value))
				{
					this.OngeAddTimeChanging(value);
					this.SendPropertyChanging();
					this._geAddTime = value;
					this.SendPropertyChanged("geAddTime");
					this.OngeAddTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uID;
		
		private string _uName;
		
		private string _uPwd;
		
		private string _uRealName;
		
		private string _uSex;
		
		private System.Nullable<int> _uAge;
		
		private string _uHobby;
		
		private string _uPhone;
		
		private string _uEmail;
		
		private string _uQQ;
		
		private string _uImage;
		
		private System.Nullable<System.DateTime> _uRegTime;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuIDChanging(int value);
    partial void OnuIDChanged();
    partial void OnuNameChanging(string value);
    partial void OnuNameChanged();
    partial void OnuPwdChanging(string value);
    partial void OnuPwdChanged();
    partial void OnuRealNameChanging(string value);
    partial void OnuRealNameChanged();
    partial void OnuSexChanging(string value);
    partial void OnuSexChanged();
    partial void OnuAgeChanging(System.Nullable<int> value);
    partial void OnuAgeChanged();
    partial void OnuHobbyChanging(string value);
    partial void OnuHobbyChanged();
    partial void OnuPhoneChanging(string value);
    partial void OnuPhoneChanged();
    partial void OnuEmailChanging(string value);
    partial void OnuEmailChanged();
    partial void OnuQQChanging(string value);
    partial void OnuQQChanged();
    partial void OnuImageChanging(string value);
    partial void OnuImageChanged();
    partial void OnuRegTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnuRegTimeChanged();
    #endregion
		
		public Users()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uID
		{
			get
			{
				return this._uID;
			}
			set
			{
				if ((this._uID != value))
				{
					this.OnuIDChanging(value);
					this.SendPropertyChanging();
					this._uID = value;
					this.SendPropertyChanged("uID");
					this.OnuIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uName", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string uName
		{
			get
			{
				return this._uName;
			}
			set
			{
				if ((this._uName != value))
				{
					this.OnuNameChanging(value);
					this.SendPropertyChanging();
					this._uName = value;
					this.SendPropertyChanged("uName");
					this.OnuNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uPwd", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string uPwd
		{
			get
			{
				return this._uPwd;
			}
			set
			{
				if ((this._uPwd != value))
				{
					this.OnuPwdChanging(value);
					this.SendPropertyChanging();
					this._uPwd = value;
					this.SendPropertyChanged("uPwd");
					this.OnuPwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uRealName", DbType="VarChar(30)")]
		public string uRealName
		{
			get
			{
				return this._uRealName;
			}
			set
			{
				if ((this._uRealName != value))
				{
					this.OnuRealNameChanging(value);
					this.SendPropertyChanging();
					this._uRealName = value;
					this.SendPropertyChanged("uRealName");
					this.OnuRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uSex", DbType="VarChar(2)")]
		public string uSex
		{
			get
			{
				return this._uSex;
			}
			set
			{
				if ((this._uSex != value))
				{
					this.OnuSexChanging(value);
					this.SendPropertyChanging();
					this._uSex = value;
					this.SendPropertyChanged("uSex");
					this.OnuSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uAge", DbType="Int")]
		public System.Nullable<int> uAge
		{
			get
			{
				return this._uAge;
			}
			set
			{
				if ((this._uAge != value))
				{
					this.OnuAgeChanging(value);
					this.SendPropertyChanging();
					this._uAge = value;
					this.SendPropertyChanged("uAge");
					this.OnuAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uHobby", DbType="VarChar(150)")]
		public string uHobby
		{
			get
			{
				return this._uHobby;
			}
			set
			{
				if ((this._uHobby != value))
				{
					this.OnuHobbyChanging(value);
					this.SendPropertyChanging();
					this._uHobby = value;
					this.SendPropertyChanged("uHobby");
					this.OnuHobbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uPhone", DbType="VarChar(20)")]
		public string uPhone
		{
			get
			{
				return this._uPhone;
			}
			set
			{
				if ((this._uPhone != value))
				{
					this.OnuPhoneChanging(value);
					this.SendPropertyChanging();
					this._uPhone = value;
					this.SendPropertyChanged("uPhone");
					this.OnuPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uEmail", DbType="VarChar(50)")]
		public string uEmail
		{
			get
			{
				return this._uEmail;
			}
			set
			{
				if ((this._uEmail != value))
				{
					this.OnuEmailChanging(value);
					this.SendPropertyChanging();
					this._uEmail = value;
					this.SendPropertyChanged("uEmail");
					this.OnuEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uQQ", DbType="VarChar(20)")]
		public string uQQ
		{
			get
			{
				return this._uQQ;
			}
			set
			{
				if ((this._uQQ != value))
				{
					this.OnuQQChanging(value);
					this.SendPropertyChanging();
					this._uQQ = value;
					this.SendPropertyChanged("uQQ");
					this.OnuQQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uImage", DbType="VarChar(100)")]
		public string uImage
		{
			get
			{
				return this._uImage;
			}
			set
			{
				if ((this._uImage != value))
				{
					this.OnuImageChanging(value);
					this.SendPropertyChanging();
					this._uImage = value;
					this.SendPropertyChanged("uImage");
					this.OnuImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uRegTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> uRegTime
		{
			get
			{
				return this._uRegTime;
			}
			set
			{
				if ((this._uRegTime != value))
				{
					this.OnuRegTimeChanging(value);
					this.SendPropertyChanging();
					this._uRegTime = value;
					this.SendPropertyChanged("uRegTime");
					this.OnuRegTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
